namespace MapleServer2.Enums
{
    public enum ItemAttribute : short
    {
        Strength = 0,
        Dexterity = 1,
        Intelligence = 2,
        Luck = 3,
        Health = 4,
        HpRegen = 5,
        HpRegenInterval = 6,
        Spirit = 7,
        SpRegen = 8,
        SpRegenInterval = 9,
        Stamina = 10,
        StaminaRegen = 11,
        StaminaRegenInterval = 12,
        AttackSpeed = 13,
        MovementSpeed = 14,
        Accuracy = 15,
        Evasion = 16,
        CriticalRate = 17,
        CriticalDamage = 18,
        CriticalEvasion = 19,
        Defense = 20,
        PerfectGuard = 21,
        JumpHeight = 22,
        PhysicalAtk = 23,
        MagicalAtk = 24,
        PhysicalRes = 25,
        MagicalRes = 26,
        MinWeaponAtk = 27,
        MaxWeaponAtk = 28,
        Damage = 29,
        Unknown = 30,
        Piercing = 31,
        MountMovementSpeed = 32,
        BonusAtk = 33,
        PetBonusAtk = 34
    }
}
