namespace Maple2Storage.Enums
{
    public enum BlackMarketCategory : short
    {
        None = 0,
        Bludgeon = 99, // 130_equip
        Dagger = 100,
        Longsword,
        Scepter,
        ThrownWeapon,
        GreatSword, 
        Bow,
        Staff,
        Cannon,
        Blade,
        Knuckle,
        Codex,
        Shield,
        Orb,
        BludgeonSkin,
        DaggerSkin,
        LongswordSkin,
        ScepterSkin,
        ThrownWeaponSkin,
        GreatSwordSkin,
        BowSkin,
        StaffSkin,
        CannonSkin,
        BladeSkin,
        KnuckleSkin,
        CodexSkin,
        ShieldSkin,
        OrbSkin,
        Suit,
        Top,
        Bottom,
        Headgear,
        Cape,
        Shoes,
        Gloves,
        Belt,
        Earring,
        Necklace,
        Ring,
        SuitSkin,
        TopSkin,
        BottomSkin,
        HeadgearSkin,
        CapeSkin,
        ShoesSkin,
        GlovesSkin,
        BeltSkin,
        EarringSkin,
        NecklaceSkin,
        RingSkin,

    }
}
