namespace Maple2Storage.Enums;

public enum ItemType
{
    None,
    Currency,
    Furnishing,
    Pet,
    Lapenshard,
    Medal,
    Earring = 12,
    Hat = 13,
    Clothes = 14,
    Pants = 15,
    Gloves = 16,
    Shoes = 17,
    Cape = 18,
    Necklace = 19,
    Ring = 20,
    Belt = 21,
    Overall = 22,
    Bludgeon = 30,
    Dagger = 31,
    Longsword = 32,
    Scepter = 33,
    ThrowingStar = 34,
    Spellbook = 40,
    Shield = 41,
    Greatsword = 50,
    Bow = 51,
    Staff = 52,
    Cannon = 53,
    Blade = 54,
    Knuckle = 55,
    Orb = 56
}
