namespace Maple2Storage.Enums;

public enum ItemHousingCategory : short
{
    None = 0,
    Bed = 1,
    Table = 2,
    SofasChairs = 3,
    Storage = 4,
    WallDecoration = 5,
    WallTiles = 6,
    Bathroom = 7,
    Lighting = 8,
    Electronics = 9,
    Fences = 10,
    NaturalTerrain = 11,
    Garden = 12,
    SpecialBlocks = 13,
    Stairs = 14,
    Doors = 15,
    CommonTerrain = 16,
    Vegetation = 17,
    InteriorDecor = 18,
    ThemedDecor = 19,
    Structures = 20,
    Traps = 21,
    Maid = 91,
    Souvenirs = 92,
    UgcBlock = 93,
    Event = 94,
    UgcBed = 95,
    UgcTable = 96,
    UgcStairs = 97,
    Ranching = 204,
    Farming = 205,
    Misc = 10000
}
