namespace MapleServer2.Enums
{
    public enum ItemSpecialAttribute : short
    {
        None = 0,
        Experience = 1,
        EnemyExp = 2,
        SwimSpeed = 3,
        DashDistance = 4,
        TonicDropRate = 5,
        GearDropRate = 6,
        TotalDamage = 7,
        CriticalDamage = 8,
        Damage = 9,
        LeaderDamage = 10,
        EliteDamage = 11,
        BossDamage = 12,
        HpRecovery = 13,
        SpRecovery = 14,
        StaminaRecovery = 15,
        SkillRecovery = 16,
        CriticalRate = 17,
        IceDamage = 18,
        FireDamage = 19,
        DarkDamage = 20,
        HolyDamage = 21,
        PoisonDamage = 22,
        ElectricDamage = 23,
        MeleeDamage = 24,
        RangedDamage = 25,
        PhysicalPierce = 26,
        MagicPierce = 27,
        IceReduce = 28,
        FireReduce = 29,
        DarkReduce = 30,
        HolyReduce = 31,
        PoisonReduce = 32,
        ElectricReduce = 33,
        StunReduce = 34,
        CooldownReduce = 35,
        DebuffReduce = 36,
        MeleeReduce = 37,
        RangedReduce = 38,
        KnockbackReduce = 39,
        MeleeStun = 40,
        RangedStun = 41,
        MeleeKnockback = 42,
        RangedKnockback = 43,
        MeleeImmobilize = 44,
        RangedImmobilize = 45,
        MeleeAoeDamage = 46,
        RangedAoeDamage = 47,
        ItemDropRate = 48,
        QuestExp = 49,
        QuestMesos = 50
    }
}