namespace MapleServer2.Enums;

public enum SystemNotice
{
    None = 0x0,
    ChooseYourName = 0x1, // s_char_input_name
    CharacterLevelJob = 0x2, //s_char_level_job
    CharacterDeleteWaiting = 0x3, //s_char_delete_waiting
    CharacterAskDelete = 0x4, // s_char_ask_delete
    CharacterAskDeleteWithWait = 0x5, // s_char_ask_delete_with_wait
    CharacterAskDeleteFinal = 0x6, // s_char_ask_delete_final
    CharacterAskDeleteConfirmCheckbox = 0x7, // s_char_ask_delete_confirm_checkbox
    CharacterAskRevival = 0x8, // s_char_ask_revival_char
    CharacterErrorCharCount = 0x9, // s_char_err_char_count
    CharacterErrorCharCountByGameEvent = 0xA, // s_char_err_char_count_by_gameevent
    CharacterErrorInputEnter2Letters = 0xB, //s_char_err_input
    CharacterCannotBeCreated = 0xC, //s_char_err_system
    CharacterErrorNameEnter2Letters = 0xD, //s_char_err_name
    CharacterErrorNameContainsForbiddenWord = 0xE, // s_char_err_ban_any
    CharacterErrorInvalidName = 0xF, //s_char_err_ban_all
    CharacterErrorNameIsTaken = 0x10, // s_char_err_already_taken
    CharacterErrorIncorrectGear = 0x11, // s_char_err_invalid_def_item
    CharacterErrorJobForbidden = 0x12, // s_char_err_job_forbidden
    CharacterErrorAbnormalActivity = 0x13, //s_char_err_creation_restriction
    CharacterErrorUnknown = 0x14, //s_char_err_unknown
    CharacterErrorExistsUgcMap = 0x15, //s_char_err_exist_ugc_map
    CharacterErrorAlreadyDeleted = 0x16, //s_char_err_already_destroy
    CharacterErrorDestroy = 0x17, //s_char_err_destroy
    CharacterErrorMisspelledName = 0x18, // s_char_err_delete_name
    CharacterErrorGuildMaster = 0x19, //s_char_err_guild_master
    CharacterErrorInGuild = 0x1A, //s_char_err_guild
    CharacterErrorItemListedInMarket = 0x1B, //s_char_err_ugc_market
    CharacterErrorItemListInBlackMarket = 0x1C, //s_char_err_black_market_count
    CharacterErrorUnreadMail = 0x1D, //s_char_err_unread_mail
    CharacterErrorNotWaitingDeletion = 0x1E, //s_char_err_no_destroy_wait
    CharacterInfoBirthday = 0x1F, //s_char_info_birthday
    CharacterInfoLevelJob = 0x20, //s_char_info_level_job
    CharacterInfoJoinAGuild = 0x21, //s_char_info_guild
    CharacterInfoCreateAHome = 0x22, //s_char_info_ugcmap
    CharacterInfoNameYourHouse = 0x23, //s_char_info_home_name
    CharacterInfoGuildName = 0x24, //s_char_info_guild_name
    CharacterInfoArchitectScore = 0x25, //s_char_info_home_commend
    CharacterInfoErrorNotFound = 0x26, //s_char_info_err_not_found
    ChangeNameDisconnect = 0x27, //s_change_charname_disconnect
    ChangeNameConfirm = 0x28, //s_change_charname_confirm
    ChangeNameErrorBadWorks = 0x29, //s_change_charname_err_bad_words
    ChangeNameErrorAlreadyTaken = 0x2A, //s_change_charname_err_already_taken
    ChangeNameErrorConsumeItem = 0x2B, //s_change_charname_err_consume_item
    ChangeNameErrorSystem = 0x2C, //s_change_charname_err_system
    UnmetGenderRequirements = 0x2D, //s_err_gender
    NoTarget = 0x2E, //s_err_target
    WrongJob = 0x2F, //s_err_job
    LowAttributes = 0x30, //s_err_stat
    InsufficientVouchers = 0x31, //s_err_lack_coupon
    InsufficientSuperChatThemes = 0x32, //s_err_lack_super_coupon
    InsufficientCurrency = 0x33, //s_err_lack_money
    InsufficientMesos = 0x34, //s_err_lack_meso
    InsufficientMerets = 0x35, //s_err_lack_merat
    InsufficientBlueMerets = 0x36, //s_err_lack_merat_blue
    InsufficientRedMerets = 0x37, //s_err_lack_merat_red
    InsufficientItems = 0x38, //s_err_lack_payment_item
    InsufficientValorTokens = 0x39, //s_err_lack_honor_token
    InsufficientTreva = 0x3A, //s_err_lack_karma_token
    InsufficientRue = 0x3B, //s_err_lack_lu_token
    InsufficientHavi = 0x3C, //s_err_lack_habi_token
    InsufficientReverseCoins = 0x3D, //s_err_lack_reverse_coin
    InsufficientMentorPoints = 0x3E, //s_err_lack_mentor_token
    InsufficientMenteePoints = 0x3F, //s_err_lack_mentee_token
    InsufficientStarPoints = 0x40, //s_err_lack_star_point
    InsufficientMesoTokens = 0x41, //s_err_lack_meso_market_token
    InvalidWhileTombstoned = 0x42, //s_err_unable
    FullInventory = 0x43, //s_err_inventory
    EmptyXInventoryTab = 0x44, //s_err_inventory_tab_full
    ItemDoesNotBelongToYou = 0x45, //s_err_dropitem_pickfail_ownership
    InsufficientHealth = 0x46, //s_err_lack_hp
    InsufficientSpirit = 0x47, //s_err_lack_sp
    InsufficientStamina = 0x48, //s_err_lack_ep
    InsufficientSupplies = 0x49, //s_err_lack_shopitem
    ItemNotFound = 0x4A, //s_err_invalid_item
    EnteredIncorrectly = 0x4B, //s_err_input
    UnableToWhisper = 0x4C, //s_err_cannot_find_user
    EnterNameToWhisper = 0x4D, //s_err_input_whisper_target
    UnableToClubChat = 0x4E, //s_err_cannot_find_club
    EnterClubNameToChat = 0x4F, //s_err_input_club
    ForcedMovementImpossible = 0x50, //s_err_cannot_move
    CannotUseDuringCombat = 0x51, //s_err_cannot_fly, s_msg_skillbook_set_disable_battle, s_error_talk_battle_state_force_talk
    UnableToDoHere = 0x52, //s_msg_item_open_massive_cant_open, s_msg_item_install_bill_board_cant_install, s_err_cannot_use_here
    UnableToUseWhileTombstoned = 0x53, //s_err_cannot_use_dead
    CannotDoYet = 0x54, //s_err_cannot_use_cooltime
    OnlyUseInLandOfDarkness = 0x55, //s_err_cannot_use_only_shadowworld
    CannotUseThatRightNow = 0x56, //s_err_require_additional_effect
    CannotUsePotionsWhileTombstoned = 0x57, //s_err_got_of_control_unable_potion
    CannotUseThatRightNow2 = 0x58, //s_err_skill_use_disable
    ConditionsNotMetToUse = 0x59, //s_err_skill_use_disable_by_require_condition
    InsufficientGuildTrophies = 0x5A, //s_err_lack_guild_trophy
    MustHaveXTrophy = 0x5B, //s_err_lack_achieve
    MustBeXRank = 0x5C, //s_err_lack_championship_grade
    ParticipateMoreThanXTimes = 0x5D, //s_err_lack_championship_join_count
    CannotWalkClimbHere = 0x5E, //s_err_cannot_use_by_function_cube_climb
    CannotJumpHere = 0x5F, //s_err_cannot_use_by_function_cube_jump
    CannotUseSkillsHere = 0x60, //s_err_cannot_use_by_function_cube_skill
    CannotPerformHere = 0x61, //s_err_cannot_use_by_function_cube_play_instrument
    CannotUseWhileFurnishing = 0x62, //s_err_cannot_use_in_design_home
    CannotPlaceNotAvailableFurnishing = 0x63, //s_err_cannot_buy_limited_item_more
    FurnishingCannotBePlaced = 0x64, //s_err_cannot_install_blueprint
    AssistantsCannotBePlaced = 0x65, //s_err_cannot_install_maid_in_practice
    LifeSkillItemsCannotBePlaced = 0x66, //s_err_cannot_install_nurturing_in_design_home
    PortalsCannotBePlaced = 0x67, //s_err_cannot_install_magic_portal
    TriggerEditorsCannotBePlaced = 0x68, //s_err_cannot_install_trigger_editor
    TriggerControlCannotBePlaced = 0x69, //s_err_cannot_install_trigger_controlobject
    MessageItemCannotBePlaced = 0x6A, //s_err_cannot_install_interior_message
    EventItemsCannotBePlaced = 0x6B, //s_err_cannot_install_event_cube
    TrophyFurnishingCannotBePlaced = 0x6C, //s_err_cannot_install_trophy_relative_cube
    AssistantStationsCannotBePlaced = 0x6D, //s_err_cannot_install_workbench_cube
    MannequinsCannotBePlaced = 0x6E, //s_err_cannot_install_fittingdoll
    UgcItemsCannotBePlaced = 0x6F, //s_err_cannot_install_ugcdesign_maidin_other
    CannotDropSummonedPet = 0x70, //s_err_cannot_destroy_petitem_summon
    CannotDropPetWithItems = 0x71, //s_err_cannot_destroy_petitem_hasitem
    XTabCannotBeAccessed = 0x72, //s_err_check_survival_with
    MaviewCannotBeUsedInTestServer = 0x73, //s_err_cannot_use_maview_in_testsvr
    ConfirmJobAdvance = 0x74, //s_job_difficulty
    InsufficientMesosToJobAdvance = 0x75, //s_err_job_not_enough_meso
    InsufficientLevelToJobAdvance = 0x76, //s_err_job_not_enough_level
    JobAdvanceOnlyByBeginner = 0x77, //s_err_job_bad_job
    UnableToTreatHealthy = 0x78, //s_err_job_no_penalty
    None2 = 0x79,
    QuestIsNotCompleted = 0x7A, //s_err_job_not_complete_quest
    None3 = 0x7B,
    ChatConditionNotApplied = 0x7C, //s_err_job_dayofweek
    YouMustJoinGuild = 0x7E, //s_err_job_guild
    EmptyXSpacesInInventory = 0x7F, //s_err_job_inventory_full
    CannotBeUsedConditions = 0x80, //s_err_job_unknown
    WearingHatCannotBeModified = 0x81, //s_mirror_err_not_editable_cp
    CannotModifyHatHiddenByTransparentBadge = 0x82, //s_mirror_err_not_editable_cp_by_transp_badge
    WearAHatToModify = 0x83, //s_mirror_err_not_equip_cp
    EmptyTabName = 0x84, //s_err_empty_tabname
    TabNameAlreadyUsed = 0x85, //s_err_duplicate_tabname
    ItemSoldOut = 0x86, //s_err_lack_itemcount, s_mesoMarket_error_alreadySoldProduct, s_cashshop_err_purchase_total_sale_count_over
    ItemCannotBeSold = 0x87, //s_item_err_cant_sell
    MustBeNearTaxiStop = 0x88, //s_err_near_taxi_station
    AlreadyOnThisMap = 0x89, //s_err_taxi_same_field
    TaxiFee = 0x8A, //s_taxi_transfer
    CallHeliRotors = 0x8B, //s_cash_taxi_transfer
    SpecialRotors = 0x8C, //s_event_free_taxi_transfer
    CannotMoveToAnotherWorld = 0x8D, //s_err_cash_taxi_continent
    CannotCallHelicopter = 0x8E, //s_err_cash_taxi_cannot_departure
    CannotGetHereByHelicopter = 0x8F, //s_err_cash_taxi_cannot_destination
    CannotUseThatTaxiRightNow = 0x90, //s_err_cash_taxi_cannot_now
    CannotBeUsedInBuildMode = 0x91, //s_err_cash_taxi_cannot_craft_mode
    CannotCallTaxiFromUnsafeLocation = 0x92, //s_err_cash_taxi_cannot_place
    RescueHeliCannotComeToRegion = 0x93, //s_err_cash_call_medic_prohibit_map
    CannotCallRescueHeliNow = 0x94, //s_err_cash_call_medic_cannot_now
    CannotCallRescueHeliWhileHealthy = 0x95, //s_err_cash_call_medic_revival_count
    CannotCallResceuHeliFromUnsafeLocation = 0x96, //s_err_cash_call_medic_cannot_place
    RescueHeliTreatedAllEffects = 0x97, //s_cash_call_medic_complete
    BrokerCannotComeToRegion = 0x98, //s_err_cash_call_market_prohibit_map
    CannotCallBrokerNow = 0x99, //s_err_cash_call_market_cannot_now
    CannotCallBrokerFromUnsafeLocation = 0x9A, //s_err_cash_call_market_cannot_place
    AlreadyUsingBlackMarket = 0x9B, //s_err_cash_call_market_cannot_already
    CannotCommunicateWithGoldusBankNow = 0x9C, //s_err_cash_call_bank_cannot_now
    AlreadyUsingBankSafe = 0x9D, //s_err_cash_call_bank_cannot_now_already
    CannotCommunicateWithGoldusBankFromUnsafeLocation = 0x9E, //s_err_cash_call_bank_cannot_now_place
    TheUseWasInterrupted = 0x9F, //s_err_cash_call_cancel
    EventMapAlreadyEnded = 0xA0, //s_err_timeevent_move_field
    CannotMoveWhileInCombat = 0xA1, //s_err_timeevent_battle
    AlreadyOnThatMap = 0xA2, //s_err_timeevent_samefield
    CannotMoveToEventMapFromThisRegion = 0xA3, //s_err_timeevent_same_continent
    CannotLinkAnotherCharacterItem = 0xA4, //s_err_itemlink_cannot_other_user
    EnterMapName = 0xA5, //s_err_worldmap_search_nothing_field
    CannotFindLocationInWorldMap = 0xA6, //s_err_worldmap_search_invisible_field
    YouCanMoveToEventGoThereNow = 0xA7, //s_worldmap_timeevent_move
    EventNoticeChat = 0xA8, //s_timeevent_notice_chat [{0:02d}:{1:02d}] {2}
    EventRevivalEffects = 0xA9, //s_revival_panelty
    LoginFailed = 0xAA, //s_fail_login
    FailedConnection = 0xAB, //s_fail_connect
    FailedCreation = 0xAC, //s_fail_char_create
    ConnectionToServerLost = 0xAD, //s_notice_shutdown
    NpcCommon = 0xAE, //s_npc_normal
    NpcLeader = 0xAF, //s_npc_leader
    NpcElite = 0xB0, //s_npc_named
    NpcBoss = 0xB1, //s_npc_boss
    NpcWorldBoss = 0xB2, //s_npc_field_boss
    NpcDungeonBoss = 0xB3, //s_npc_dungeon_boss
    NpcFriendly = 0xB4, //s_npc_friendly
    ItemRequiredWeapon = 0xB5, //s_item_require_weapon
    ItemCreatedBy = 0xB6, //s_item_edit_time "Created by {0} ({2}/{3}/{1} - {4:02d}:{5:02d}:{6:02d})"
    ItemExpires = 0xB7, //s_item_end_time "Expires {1}/{2}/{0} {3:02d}:{4:02d}"
    ItemExpired = 0xB8, //s_item_end_time_expired
    ItemMaidEmployed = 0xB9, //s_item_end_time_maid
    ItemMaidExpired = 0xBA, //s_item_end_time_maid_expired
    ItemPcBangUntil = 0xBB, //s_item_end_time_pcbang
    ItemPcBangExpired = 0xBC, //s_item_end_time_pcbang_expired
    TemporaryItem = 0xBD, //s_item_end_time_tooltip
    TemporaryItemNewLine = 0xBE, //s_item_end_time_tooltip_expiration
    TemporaryItemOnlyInCafe = 0xBF, //s_item_end_time_tooltip_pcbang
    PurchasingItemEmploysMaid = 0xC0, //s_item_end_time_tooltip_maid
    UsagePeriodWillBeginOnceMailReceived = 0xC1, //s_item_end_time_when_item_get_tooltip
    UsagePeriodWillBeginOnceMailReceivedPcBang = 0xC2, //s_item_end_time_when_item_get_tooltip_pcbang
    MaidWillBeEmployedStartingWithMailReceived = 0xC3, //s_item_end_time_when_item_get_tooltip_maid
    ItemDayMessage = 0xC4, //s_item_word_d
    ItemHourMessage = 0xC5, //s_item_word_h
    ItemMinuteMessage = 0xC6, //s_item_word_m
    ItemActiveSkill = 0xC7, //s_item_type_active
    ItemActionSkill = 0xC8, //s_item_type_passive
    ItemTwoHanded = 0xC9, //s_item_type_twohand
    ItemOffHand = 0xCA, //s_item_type_lefthand
    ItemMainHand = 0xCB, //s_item_type_righthand
    ItemSystemError = 0xCC, //s_itembreak_unknown_err
    ItemCannotBeEquipped = 0xCD, //s_item_err_puton
    ItemCannotBeRemoved = 0xCE, //s_item_err_putoff
    ItemBeingWornCannotBeDestroyed = 0xCF, //s_item_err_destroy_equip
    YouDontHaveCorrectWeaponEquipped = 0xD0, //s_item_err_no_weapon
    CannotBeUsedWithCurrentWeapon = 0xD1, //s_item_err_invalid_weapon
    SlotCannotBeUsed = 0xD2, //s_item_err_Invalid_slot
    UnequipWeaponSkinFirst = 0xD3, //s_item_err_cash_slot
    OutfitMustBeRemovedFirst = 0xD4, //s_item_err_cash_putoff
    ChangingMainHandWeaponFromTwoHandWeapon = 0xD5, //s_item_err_twohand
    ItemCannotBeDiscarded = 0xD6, //s_item_err_drop
    ItemWillBeDestroyedOnceThrownAway = 0xD7, //s_item_err_cannot_drop
    ItemIsBoundDiscardingWillDestroyIt = 0xD8, //s_item_err_cannot_drop_if_binding
    ItemIsBoundCannotWithdraw = 0xD9, //s_item_err_binding_destroy
    ItemisBoundCannotTakeFromMannequin = 0xDA, //s_item_err_binding_destroy_at_fittingdoll
    GemstoneIsCharacterBound = 0xDB, //s_item_err_binditem_in_socket_store_out
    UsedWorldChatVoucher = 0xAE2,
    UsedChannelChatVoucher = 0xAE3,
    UsedReviveVoucher = 0xAE5,
    UsedPetNameVoucher = 0xAE6,
    CannotFishHere = 0xC00,
    GravityChanged = 0xC87, // The atmosphere around you has changed. Something has altered the law of gravity itself.
    RandomNumberSelection = 0xCB9,
    CantUseRollCommand = 0xCBA, // The roll command is only possible through party chat. Can be used through normal chat when inside a home or dungeon.
    RandomGroupAssignment = 0xCBB,
    RandomSelection = 0xCBC,
    PremiumExtended = 0xCE7,
    PremiumActivated = 0xCE8,
    CharacterNotFound = 0xCFA,
    BuddyBadgeMailedToUser = 0xD00
}
