//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public long Character_ID { get; set; }
        public long Account_ID { get; set; }
        public short Level { get; set; }
        public string Name { get; set; }
        public Nullable<byte> Gender { get; set; }
        public Nullable<short> Job_ID { get; set; }
        public Nullable<long> Mesos { get; set; }
        public Nullable<int> Map_ID { get; set; }
        public System.DateTime Creation_Time { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
