using Maple2Storage.Types;
using MapleServer2.Database.Types;

namespace MapleServer2.Database
{
    public static class MeretMarketItemSeeding
    {
        public static void Seed()
        {
            List<MeretMarketItem> market = new List<MeretMarketItem>()
            {
                new MeretMarketItem()
            {

                Category = MeretMarketCategory.Functional,
                MarketId = 140300010,
                ItemId = 70100005,
                Rarity = 1,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
                Price = 360,
                SalePrice = 360,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Functional,
                MarketId = 140300020,
                ItemId = 70100004,
                Rarity = 1,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
                Price = 140,
                SalePrice = 140,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Functional,
                MarketId = 140300025,
                ItemId = 70100001,
                Rarity = 1,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
                Price = 1450,
                SalePrice = 1450,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Functional,
                MarketId = 140300030,
                ItemId = 30000896,
                Rarity = 1,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
                Price = 650,
                SalePrice = 650,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Functional,
                MarketId = 140300040,
                ItemId = 20302314,
                Rarity = 1,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
                Price = 650,
                SalePrice = 650,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Functional,
                MarketId = 140300050,
                ItemId = 20300011,
                Rarity = 1,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
                Price = 30,
                SalePrice = 30,
                AdditionalQuantities = new List<MeretMarketItem>()
                {
                    new MeretMarketItem()
                    {
                         MarketId = 140300051,
                         ParentMarketId = 140300050,
                         ItemId = 20300011,
                         Rarity = 1,
                         Quantity = 5,
                         TokenType = MeretMarketCurrencyType.Meret,
                         SellBeginTime = 1262304000,
                         SellEndTime = 4102444800,
                         JobRequirement = MeretMarketJobRequirement.All,
                         Price = 150,
                         SalePrice = 150,
                    },
                    new MeretMarketItem()
                    {
                         MarketId = 140300052,
                         ParentMarketId = 140300050,
                         ItemId = 20300011,
                         Rarity = 1,
                         Quantity = 10,
                         TokenType = MeretMarketCurrencyType.Meret,
                         SellBeginTime = 1262304000,
                         SellEndTime = 4102444800,
                         JobRequirement = MeretMarketJobRequirement.All,
                         Price = 300,
                         SalePrice = 300,
                    },
                    new MeretMarketItem()
                    {
                         MarketId = 140300053,
                         ParentMarketId = 140300050,
                         ItemId = 20300011,
                         Rarity = 1,
                         Quantity = 30,
                         TokenType = MeretMarketCurrencyType.Meret,
                         SellBeginTime = 1262304000,
                         SellEndTime = 4102444800,
                         JobRequirement = MeretMarketJobRequirement.All,
                         Price = 900,
                         SalePrice = 900,
                    }
                }
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Functional,
                MarketId = 140300060,
                ItemId = 20000004,
                Rarity = 1,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
                Price = 7,
                SalePrice = 7,
                AdditionalQuantities = new List<MeretMarketItem>()
                {
                    new MeretMarketItem()
                    {
                         MarketId = 140300061,
                         ParentMarketId = 140300060,
                         ItemId = 20000004,
                         Rarity = 1,
                         Quantity = 10,
                         TokenType = MeretMarketCurrencyType.Meret,
                         SellBeginTime = 1262304000,
                         SellEndTime = 4102444800,
                         JobRequirement = MeretMarketJobRequirement.All,
                         Price = 70,
                         SalePrice = 65,
                    },
                    new MeretMarketItem()
                    {
                         MarketId = 140300062,
                         ParentMarketId = 140300060,
                         ItemId = 20000004,
                         Rarity = 1,
                         Quantity = 50,
                         TokenType = MeretMarketCurrencyType.Meret,
                         SellBeginTime = 1262304000,
                         SellEndTime = 4102444800,
                         JobRequirement = MeretMarketJobRequirement.All,
                         Price = 350,
                         SalePrice = 300,
                    },
                    new MeretMarketItem()
                    {
                         MarketId = 140300063,
                         ParentMarketId = 140300060,
                         ItemId = 20000004,
                         Rarity = 1,
                         Quantity = 100,
                         TokenType = MeretMarketCurrencyType.Meret,
                         SellBeginTime = 1262304000,
                         SellEndTime = 4102444800,
                         JobRequirement = MeretMarketJobRequirement.All,
                         Price = 700,
                         SalePrice = 550,
                    }
                }
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Functional,
                MarketId = 140300070,
                ItemId = 20300226,
                Rarity = 1,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
                Price = 5,
                SalePrice = 5,
                AdditionalQuantities = new List<MeretMarketItem>()
                {
                    new MeretMarketItem()
                    {
                         MarketId = 140300071,
                         ParentMarketId = 140300070,
                         ItemId = 20300226,
                         Rarity = 1,
                         Quantity = 10,
                         TokenType = MeretMarketCurrencyType.Meret,
                         SellBeginTime = 1262304000,
                         SellEndTime = 4102444800,
                         JobRequirement = MeretMarketJobRequirement.All,
                         Price = 50,
                         SalePrice = 45,
                    },
                    new MeretMarketItem()
                    {
                         MarketId = 140300072,
                         ParentMarketId = 140300070,
                         ItemId = 20300226,
                         Rarity = 1,
                         Quantity = 50,
                         TokenType = MeretMarketCurrencyType.Meret,
                         SellBeginTime = 1262304000,
                         SellEndTime = 4102444800,
                         JobRequirement = MeretMarketJobRequirement.All,
                         Price = 250,
                         SalePrice = 200,
                    },
                    new MeretMarketItem()
                    {
                         MarketId = 140300073,
                         ParentMarketId = 140300070,
                         ItemId = 20300226,
                         Rarity = 1,
                         Quantity = 100,
                         TokenType = MeretMarketCurrencyType.Meret,
                         SellBeginTime = 1262304000,
                         SellEndTime = 4102444800,
                         JobRequirement = MeretMarketJobRequirement.All,
                         Price = 500,
                         SalePrice = 380,
                    }
                }
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Functional,
                MarketId = 140300080,
                ItemId = 20301114,
                Rarity = 1,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
                Price = 990,
                SalePrice = 990,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Functional,
                MarketId = 140300090,
                ItemId = 20300225,
                Rarity = 1,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
                Price = 790,
                SalePrice = 790,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Functional,
                MarketId = 140300100,
                ItemId = 20300224,
                Rarity = 1,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
                Price = 1390,
                SalePrice = 1390,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Functional,
                MarketId = 140300110,
                ItemId = 20300222,
                Rarity = 1,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
                Price = 990,
                SalePrice = 990,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Functional,
                MarketId = 140300120,
                ItemId = 20300054,
                Rarity = 1,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
                Price = 150,
                SalePrice = 150,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Functional,
                MarketId = 140300130,
                ItemId = 20300046,
                Rarity = 1,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
                Price = 10,
                SalePrice = 10,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Functional,
                MarketId = 140300140,
                ItemId = 20300089,
                Rarity = 1,
                Quantity = 1,
                Duration = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
                Price = 60,
                SalePrice = 60,
                AdditionalQuantities = new List<MeretMarketItem>()
                {
                    new MeretMarketItem()
                    {
                         MarketId = 140300141,
                         ParentMarketId = 140300140,
                         ItemId = 20300089,
                         Rarity = 1,
                         Quantity = 1,
                         Duration = 7,
                         TokenType = MeretMarketCurrencyType.Meret,
                         SellBeginTime = 1262304000,
                         SellEndTime = 4102444800,
                         JobRequirement = MeretMarketJobRequirement.All,
                         Price = 420,
                         SalePrice = 270,
                    }
                }
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Lifestyle,
                MarketId = 140600000,
                ItemId = 34000088,
                Rarity = 3,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                Price = 500,
                SalePrice = 500,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Lifestyle,
                MarketId = 140600010,
                ItemId = 34000089,
                Rarity = 3,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                Price = 500,
                SalePrice = 500,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Lifestyle,
                MarketId = 140600020,
                ItemId = 34000090,
                Rarity = 3,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                Price = 500,
                SalePrice = 500,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Lifestyle,
                MarketId = 140600030,
                ItemId = 34000071,
                Rarity = 3,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                Price = 500,
                SalePrice = 500,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Lifestyle,
                MarketId = 140600040,
                ItemId = 34000070,
                Rarity = 3,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                Price = 500,
                SalePrice = 500,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Lifestyle,
                MarketId = 140600050,
                ItemId = 34000049,
                Rarity = 3,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                Price = 500,
                SalePrice = 500,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Lifestyle,
                MarketId = 140600060,
                ItemId = 34000048,
                Rarity = 3,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                Price = 500,
                SalePrice = 500,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Lifestyle,
                MarketId = 140600070,
                ItemId = 34000041,
                Rarity = 3,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                Price = 500,
                SalePrice = 500,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Lifestyle,
                MarketId = 140600080,
                ItemId = 34000040,
                Rarity = 3,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                Price = 500,
                SalePrice = 500,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Lifestyle,
                MarketId = 140600090,
                ItemId = 34000039,
                Rarity = 3,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                Price = 500,
                SalePrice = 500,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Lifestyle,
                MarketId = 140600100,
                ItemId = 34000035,
                Rarity = 3,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                Price = 500,
                SalePrice = 500,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Lifestyle,
                MarketId = 140600110,
                ItemId = 34000036,
                Rarity = 3,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                Price = 500,
                SalePrice = 500,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Lifestyle,
                MarketId = 140600120,
                ItemId = 34000037,
                Rarity = 3,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                Price = 500,
                SalePrice = 500,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Lifestyle,
                MarketId = 140600130,
                ItemId = 34000028,
                Rarity = 3,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                Price = 500,
                SalePrice = 500,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Lifestyle,
                MarketId = 140600140,
                ItemId = 34000027,
                Rarity = 3,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                Price = 500,
                SalePrice = 500,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Lifestyle,
                MarketId = 140600150,
                ItemId = 34000029,
                Rarity = 3,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                Price = 500,
                SalePrice = 500,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Lifestyle,
                MarketId = 140600160,
                ItemId = 34000024,
                Rarity = 3,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                Price = 500,
                SalePrice = 500,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Lifestyle,
                MarketId = 140600170,
                ItemId = 34000025,
                Rarity = 3,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                Price = 500,
                SalePrice = 500,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Lifestyle,
                MarketId = 140600180,
                ItemId = 34000026,
                Rarity = 3,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                Price = 500,
                SalePrice = 500,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Lifestyle,
                MarketId = 140600190,
                ItemId = 34000021,
                Rarity = 3,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                Price = 500,
                SalePrice = 500,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Lifestyle,
                MarketId = 140600200,
                ItemId = 34000022,
                Rarity = 3,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                Price = 500,
                SalePrice = 500,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Lifestyle,
                MarketId = 140600210,
                ItemId = 34000023,
                Rarity = 3,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                Price = 500,
                SalePrice = 500,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Lifestyle,
                MarketId = 140600220,
                ItemId = 34000013,
                Rarity = 3,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                Price = 500,
                SalePrice = 500,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Lifestyle,
                MarketId = 140600230,
                ItemId = 34000014,
                Rarity = 3,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                Price = 500,
                SalePrice = 500,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Lifestyle,
                MarketId = 140600240,
                ItemId = 34000015,
                Rarity = 3,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                Price = 500,
                SalePrice = 500,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Lifestyle,
                MarketId = 140600250,
                ItemId = 34000012,
                Rarity = 3,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                Price = 500,
                SalePrice = 500,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Lifestyle,
                MarketId = 140600260,
                ItemId = 34000011,
                Rarity = 3,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                Price = 500,
                SalePrice = 500,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Lifestyle,
                MarketId = 140600270,
                ItemId = 34000010,
                Rarity = 3,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                Price = 500,
                SalePrice = 500,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Lifestyle,
                MarketId = 140600280,
                ItemId = 34000009,
                Rarity = 3,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                Price = 500,
                SalePrice = 500,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Lifestyle,
                MarketId = 140600290,
                ItemId = 34000008,
                Rarity = 3,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                Price = 500,
                SalePrice = 500,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                JobRequirement = MeretMarketJobRequirement.All,
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Promo,
                MarketId = 10000000,
                ItemId = 22002001,
                Rarity = 4,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                Price = 120,
                SalePrice = 100,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                PromoBannerBeginTime = 1262304000,
                PromoBannerEndTime = 4102444800,
                ShowSaleTime = true,
                Banner = new Banner
                {
                    Name = "homeproduct_emulator",
                    Type = BannerType.merat,
                    Language = BannerLanguage.All,
                    ImageUrl = "https://i.imgur.com/TV47C2m.png",
                    BeginTime = 1262304000,
                    EndTime = 4102444800
                },
                JobRequirement = MeretMarketJobRequirement.All,
                AdditionalQuantities = new List<MeretMarketItem>()
                {
                    new MeretMarketItem()
                    {
                         MarketId = 10000001,
                         ParentMarketId = 10000000,
                         ItemId = 22002001,
                         Rarity = 4,
                         Quantity = 10,
                         TokenType = MeretMarketCurrencyType.Meret,
                         SellBeginTime = 1262304000,
                         SellEndTime = 4102444800,
                         JobRequirement = MeretMarketJobRequirement.All,
                         Price = 1200,
                         SalePrice = 900,
                    },
                    new MeretMarketItem()
                    {
                         MarketId = 10000002,
                         ParentMarketId = 10000000,
                         ItemId = 22002001,
                         Rarity = 4,
                         Quantity = 50,
                         TokenType = MeretMarketCurrencyType.Meret,
                         SellBeginTime = 1262304000,
                         SellEndTime = 4102444800,
                         JobRequirement = MeretMarketJobRequirement.All,
                         Price = 6000,
                         SalePrice = 5000,
                    }
                }
            },
                new MeretMarketItem()
            {
                Category = MeretMarketCategory.Promo,
                MarketId = 10000010,
                ItemId = 22001010,
                Rarity = 4,
                Quantity = 1,
                TokenType = MeretMarketCurrencyType.Meret,
                Price = 130,
                SalePrice = 100,
                SellBeginTime = 1262304000,
                SellEndTime = 4102444800,
                PromoBannerBeginTime = 1262304000,
                PromoBannerEndTime = 4102444800,
                ShowSaleTime = false,
                PromoFlag = MeretMarketPromoFlag.PinkGift,
                JobRequirement = MeretMarketJobRequirement.All,
                AdditionalQuantities = new List<MeretMarketItem>()
                {
                    new MeretMarketItem()
                    {
                        MarketId = 10000011,
                        ParentMarketId = 10000010,
                        ItemId = 22001010,
                        Rarity = 4,
                        Quantity = 10,
                        TokenType = MeretMarketCurrencyType.Meret,
                        SellBeginTime = 1262304000,
                        SellEndTime = 4102444800,
                        JobRequirement = MeretMarketJobRequirement.All,
                        Price = 1300,
                        SalePrice = 950,
                    },
                    new MeretMarketItem()
                    {
                         MarketId = 10000012,
                         ParentMarketId = 10000010,
                         ItemId = 22001010,
                         Rarity = 4,
                         Quantity = 50,
                         TokenType = MeretMarketCurrencyType.Meret,
                         SellBeginTime = 1262304000,
                         SellEndTime = 4102444800,
                         JobRequirement = MeretMarketJobRequirement.All,
                         Price = 6500,
                         SalePrice = 5200,
                    }
                }
            }
        };
            DatabaseManager.InsertMeretMarketItems(market);
        }
    }
}
